spring:
  profiles: Dev 
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/${dbName}?useSSL=false
      username: ${userName}
      password: ${dbPassword}
      